# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q22_invoice import Q22Invoice  # noqa: F401,E501
from ods_api_server.models.q22_invoice_list import Q22InvoiceList  # noqa: F401,E501
from ods_api_server import util


class AllOftnsModifyInvoiceV4ModifyInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice: List[Q22Invoice]=None):  # noqa: E501
        """AllOftnsModifyInvoiceV4ModifyInvoice - a model defined in Swagger

        :param invoice: The invoice of this AllOftnsModifyInvoiceV4ModifyInvoice.  # noqa: E501
        :type invoice: List[Q22Invoice]
        """
        self.swagger_types = {
            'invoice': List[Q22Invoice]
        }

        self.attribute_map = {
            'invoice': 'Invoice'
        }
        self._invoice = invoice

    @classmethod
    def from_dict(cls, dikt) -> 'AllOftnsModifyInvoiceV4ModifyInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOftns_ModifyInvoiceV4ModifyInvoice of this AllOftnsModifyInvoiceV4ModifyInvoice.  # noqa: E501
        :rtype: AllOftnsModifyInvoiceV4ModifyInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice(self) -> List[Q22Invoice]:
        """Gets the invoice of this AllOftnsModifyInvoiceV4ModifyInvoice.


        :return: The invoice of this AllOftnsModifyInvoiceV4ModifyInvoice.
        :rtype: List[Q22Invoice]
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice: List[Q22Invoice]):
        """Sets the invoice of this AllOftnsModifyInvoiceV4ModifyInvoice.


        :param invoice: The invoice of this AllOftnsModifyInvoiceV4ModifyInvoice.
        :type invoice: List[Q22Invoice]
        """
        if invoice is None:
            raise ValueError("Invalid value for `invoice`, must not be `None`")  # noqa: E501

        self._invoice = invoice
