# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q12_document import Q12Document  # noqa: F401,E501
from ods_api_server.models.q12_documents import Q12Documents  # noqa: F401,E501
from ods_api_server import util


class AllOfq12PaymentLineDocuments(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, document: List[Q12Document]=None):  # noqa: E501
        """AllOfq12PaymentLineDocuments - a model defined in Swagger

        :param document: The document of this AllOfq12PaymentLineDocuments.  # noqa: E501
        :type document: List[Q12Document]
        """
        self.swagger_types = {
            'document': List[Q12Document]
        }

        self.attribute_map = {
            'document': 'Document'
        }
        self._document = document

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfq12PaymentLineDocuments':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfq12_PaymentLineDocuments of this AllOfq12PaymentLineDocuments.  # noqa: E501
        :rtype: AllOfq12PaymentLineDocuments
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document(self) -> List[Q12Document]:
        """Gets the document of this AllOfq12PaymentLineDocuments.


        :return: The document of this AllOfq12PaymentLineDocuments.
        :rtype: List[Q12Document]
        """
        return self._document

    @document.setter
    def document(self, document: List[Q12Document]):
        """Sets the document of this AllOfq12PaymentLineDocuments.


        :param document: The document of this AllOfq12PaymentLineDocuments.
        :type document: List[Q12Document]
        """
        if document is None:
            raise ValueError("Invalid value for `document`, must not be `None`")  # noqa: E501

        self._document = document
