# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q26_hotel_credit_card_info import Q26HotelCreditCardInfo  # noqa: F401,E501
from ods_api_server.models.q26_hotel_credit_card_info_list import Q26HotelCreditCardInfoList  # noqa: F401,E501
from ods_api_server import util


class AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, hotel_credit_card_info: List[Q26HotelCreditCardInfo]=None):  # noqa: E501
        """AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo - a model defined in Swagger

        :param hotel_credit_card_info: The hotel_credit_card_info of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.  # noqa: E501
        :type hotel_credit_card_info: List[Q26HotelCreditCardInfo]
        """
        self.swagger_types = {
            'hotel_credit_card_info': List[Q26HotelCreditCardInfo]
        }

        self.attribute_map = {
            'hotel_credit_card_info': 'HotelCreditCardInfo'
        }
        self._hotel_credit_card_info = hotel_credit_card_info

    @classmethod
    def from_dict(cls, dikt) -> 'AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOftns_ModifyHotelCreditCardInfoModifyCreditCardInfo of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.  # noqa: E501
        :rtype: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def hotel_credit_card_info(self) -> List[Q26HotelCreditCardInfo]:
        """Gets the hotel_credit_card_info of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.


        :return: The hotel_credit_card_info of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.
        :rtype: List[Q26HotelCreditCardInfo]
        """
        return self._hotel_credit_card_info

    @hotel_credit_card_info.setter
    def hotel_credit_card_info(self, hotel_credit_card_info: List[Q26HotelCreditCardInfo]):
        """Sets the hotel_credit_card_info of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.


        :param hotel_credit_card_info: The hotel_credit_card_info of this AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo.
        :type hotel_credit_card_info: List[Q26HotelCreditCardInfo]
        """
        if hotel_credit_card_info is None:
            raise ValueError("Invalid value for `hotel_credit_card_info`, must not be `None`")  # noqa: E501

        self._hotel_credit_card_info = hotel_credit_card_info
