# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.tns_change_contact_information import TnsChangeContactInformation  # noqa: F401,E501
from ods_api_server import util


class AllOfChangeContactInformationChangeContactInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contact_information: object=None):  # noqa: E501
        """AllOfChangeContactInformationChangeContactInformation - a model defined in Swagger

        :param contact_information: The contact_information of this AllOfChangeContactInformationChangeContactInformation.  # noqa: E501
        :type contact_information: object
        """
        self.swagger_types = {
            'contact_information': object
        }

        self.attribute_map = {
            'contact_information': 'contactInformation'
        }
        self._contact_information = contact_information

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfChangeContactInformationChangeContactInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfChangeContactInformationChangeContactInformation of this AllOfChangeContactInformationChangeContactInformation.  # noqa: E501
        :rtype: AllOfChangeContactInformationChangeContactInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_information(self) -> object:
        """Gets the contact_information of this AllOfChangeContactInformationChangeContactInformation.


        :return: The contact_information of this AllOfChangeContactInformationChangeContactInformation.
        :rtype: object
        """
        return self._contact_information

    @contact_information.setter
    def contact_information(self, contact_information: object):
        """Sets the contact_information of this AllOfChangeContactInformationChangeContactInformation.


        :param contact_information: The contact_information of this AllOfChangeContactInformationChangeContactInformation.
        :type contact_information: object
        """
        if contact_information is None:
            raise ValueError("Invalid value for `contact_information`, must not be `None`")  # noqa: E501

        self._contact_information = contact_information
