# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q14_customer import Q14Customer  # noqa: F401,E501
from ods_api_server.models.q14_customer_list import Q14CustomerList  # noqa: F401,E501
from ods_api_server import util


class AllOftnsChangeCustomerAddressV2CustomerAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer: List[Q14Customer]=None):  # noqa: E501
        """AllOftnsChangeCustomerAddressV2CustomerAddress - a model defined in Swagger

        :param customer: The customer of this AllOftnsChangeCustomerAddressV2CustomerAddress.  # noqa: E501
        :type customer: List[Q14Customer]
        """
        self.swagger_types = {
            'customer': List[Q14Customer]
        }

        self.attribute_map = {
            'customer': 'Customer'
        }
        self._customer = customer

    @classmethod
    def from_dict(cls, dikt) -> 'AllOftnsChangeCustomerAddressV2CustomerAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOftns_ChangeCustomerAddressV2CustomerAddress of this AllOftnsChangeCustomerAddressV2CustomerAddress.  # noqa: E501
        :rtype: AllOftnsChangeCustomerAddressV2CustomerAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer(self) -> List[Q14Customer]:
        """Gets the customer of this AllOftnsChangeCustomerAddressV2CustomerAddress.


        :return: The customer of this AllOftnsChangeCustomerAddressV2CustomerAddress.
        :rtype: List[Q14Customer]
        """
        return self._customer

    @customer.setter
    def customer(self, customer: List[Q14Customer]):
        """Sets the customer of this AllOftnsChangeCustomerAddressV2CustomerAddress.


        :param customer: The customer of this AllOftnsChangeCustomerAddressV2CustomerAddress.
        :type customer: List[Q14Customer]
        """
        if customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")  # noqa: E501

        self._customer = customer
