# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q16_invoice import Q16Invoice  # noqa: F401,E501
from ods_api_server.models.q16_invoice_list import Q16InvoiceList  # noqa: F401,E501
from ods_api_server import util


class AllOftnsModifyInvoiceV2ModifyInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice: List[Q16Invoice]=None):  # noqa: E501
        """AllOftnsModifyInvoiceV2ModifyInvoice - a model defined in Swagger

        :param invoice: The invoice of this AllOftnsModifyInvoiceV2ModifyInvoice.  # noqa: E501
        :type invoice: List[Q16Invoice]
        """
        self.swagger_types = {
            'invoice': List[Q16Invoice]
        }

        self.attribute_map = {
            'invoice': 'Invoice'
        }
        self._invoice = invoice

    @classmethod
    def from_dict(cls, dikt) -> 'AllOftnsModifyInvoiceV2ModifyInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOftns_ModifyInvoiceV2ModifyInvoice of this AllOftnsModifyInvoiceV2ModifyInvoice.  # noqa: E501
        :rtype: AllOftnsModifyInvoiceV2ModifyInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice(self) -> List[Q16Invoice]:
        """Gets the invoice of this AllOftnsModifyInvoiceV2ModifyInvoice.


        :return: The invoice of this AllOftnsModifyInvoiceV2ModifyInvoice.
        :rtype: List[Q16Invoice]
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice: List[Q16Invoice]):
        """Sets the invoice of this AllOftnsModifyInvoiceV2ModifyInvoice.


        :param invoice: The invoice of this AllOftnsModifyInvoiceV2ModifyInvoice.
        :type invoice: List[Q16Invoice]
        """
        if invoice is None:
            raise ValueError("Invalid value for `invoice`, must not be `None`")  # noqa: E501

        self._invoice = invoice
