# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.tns_modify_hotel_credit_card_info import TnsModifyHotelCreditCardInfo  # noqa: F401,E501
from ods_api_server import util


class AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_credit_card_info: object=None):  # noqa: E501
        """AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo - a model defined in Swagger

        :param modify_credit_card_info: The modify_credit_card_info of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.  # noqa: E501
        :type modify_credit_card_info: object
        """
        self.swagger_types = {
            'modify_credit_card_info': object
        }

        self.attribute_map = {
            'modify_credit_card_info': 'modifyCreditCardInfo'
        }
        self._modify_credit_card_info = modify_credit_card_info

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.  # noqa: E501
        :rtype: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_credit_card_info(self) -> object:
        """Gets the modify_credit_card_info of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.


        :return: The modify_credit_card_info of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.
        :rtype: object
        """
        return self._modify_credit_card_info

    @modify_credit_card_info.setter
    def modify_credit_card_info(self, modify_credit_card_info: object):
        """Sets the modify_credit_card_info of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.


        :param modify_credit_card_info: The modify_credit_card_info of this AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo.
        :type modify_credit_card_info: object
        """
        if modify_credit_card_info is None:
            raise ValueError("Invalid value for `modify_credit_card_info`, must not be `None`")  # noqa: E501

        self._modify_credit_card_info = modify_credit_card_info
