# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.tns_change_invoice_address import TnsChangeInvoiceAddress  # noqa: F401,E501
from ods_api_server import util


class AllOfChangeInvoiceAddressChangeInvoiceAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_address: object=None):  # noqa: E501
        """AllOfChangeInvoiceAddressChangeInvoiceAddress - a model defined in Swagger

        :param invoice_address: The invoice_address of this AllOfChangeInvoiceAddressChangeInvoiceAddress.  # noqa: E501
        :type invoice_address: object
        """
        self.swagger_types = {
            'invoice_address': object
        }

        self.attribute_map = {
            'invoice_address': 'invoiceAddress'
        }
        self._invoice_address = invoice_address

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfChangeInvoiceAddressChangeInvoiceAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfChangeInvoiceAddressChangeInvoiceAddress of this AllOfChangeInvoiceAddressChangeInvoiceAddress.  # noqa: E501
        :rtype: AllOfChangeInvoiceAddressChangeInvoiceAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_address(self) -> object:
        """Gets the invoice_address of this AllOfChangeInvoiceAddressChangeInvoiceAddress.


        :return: The invoice_address of this AllOfChangeInvoiceAddressChangeInvoiceAddress.
        :rtype: object
        """
        return self._invoice_address

    @invoice_address.setter
    def invoice_address(self, invoice_address: object):
        """Sets the invoice_address of this AllOfChangeInvoiceAddressChangeInvoiceAddress.


        :param invoice_address: The invoice_address of this AllOfChangeInvoiceAddressChangeInvoiceAddress.
        :type invoice_address: object
        """
        if invoice_address is None:
            raise ValueError("Invalid value for `invoice_address`, must not be `None`")  # noqa: E501

        self._invoice_address = invoice_address
