# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_change_customer_address_change_customer_address import AllOfChangeCustomerAddressChangeCustomerAddress  # noqa: F401,E501
from ods_api_server import util


class ChangeCustomerAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_customer_address: AllOfChangeCustomerAddressChangeCustomerAddress=None):  # noqa: E501
        """ChangeCustomerAddress - a model defined in Swagger

        :param change_customer_address: The change_customer_address of this ChangeCustomerAddress.  # noqa: E501
        :type change_customer_address: AllOfChangeCustomerAddressChangeCustomerAddress
        """
        self.swagger_types = {
            'change_customer_address': AllOfChangeCustomerAddressChangeCustomerAddress
        }

        self.attribute_map = {
            'change_customer_address': 'ChangeCustomerAddress'
        }
        self._change_customer_address = change_customer_address

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeCustomerAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeCustomerAddress of this ChangeCustomerAddress.  # noqa: E501
        :rtype: ChangeCustomerAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_customer_address(self) -> AllOfChangeCustomerAddressChangeCustomerAddress:
        """Gets the change_customer_address of this ChangeCustomerAddress.


        :return: The change_customer_address of this ChangeCustomerAddress.
        :rtype: AllOfChangeCustomerAddressChangeCustomerAddress
        """
        return self._change_customer_address

    @change_customer_address.setter
    def change_customer_address(self, change_customer_address: AllOfChangeCustomerAddressChangeCustomerAddress):
        """Sets the change_customer_address of this ChangeCustomerAddress.


        :param change_customer_address: The change_customer_address of this ChangeCustomerAddress.
        :type change_customer_address: AllOfChangeCustomerAddressChangeCustomerAddress
        """
        if change_customer_address is None:
            raise ValueError("Invalid value for `change_customer_address`, must not be `None`")  # noqa: E501

        self._change_customer_address = change_customer_address
