# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_change_invoice_address_change_invoice_address import AllOfChangeInvoiceAddressChangeInvoiceAddress  # noqa: F401,E501
from ods_api_server import util


class ChangeInvoiceAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_invoice_address: AllOfChangeInvoiceAddressChangeInvoiceAddress=None):  # noqa: E501
        """ChangeInvoiceAddress - a model defined in Swagger

        :param change_invoice_address: The change_invoice_address of this ChangeInvoiceAddress.  # noqa: E501
        :type change_invoice_address: AllOfChangeInvoiceAddressChangeInvoiceAddress
        """
        self.swagger_types = {
            'change_invoice_address': AllOfChangeInvoiceAddressChangeInvoiceAddress
        }

        self.attribute_map = {
            'change_invoice_address': 'ChangeInvoiceAddress'
        }
        self._change_invoice_address = change_invoice_address

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeInvoiceAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeInvoiceAddress of this ChangeInvoiceAddress.  # noqa: E501
        :rtype: ChangeInvoiceAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_invoice_address(self) -> AllOfChangeInvoiceAddressChangeInvoiceAddress:
        """Gets the change_invoice_address of this ChangeInvoiceAddress.


        :return: The change_invoice_address of this ChangeInvoiceAddress.
        :rtype: AllOfChangeInvoiceAddressChangeInvoiceAddress
        """
        return self._change_invoice_address

    @change_invoice_address.setter
    def change_invoice_address(self, change_invoice_address: AllOfChangeInvoiceAddressChangeInvoiceAddress):
        """Sets the change_invoice_address of this ChangeInvoiceAddress.


        :param change_invoice_address: The change_invoice_address of this ChangeInvoiceAddress.
        :type change_invoice_address: AllOfChangeInvoiceAddressChangeInvoiceAddress
        """
        if change_invoice_address is None:
            raise ValueError("Invalid value for `change_invoice_address`, must not be `None`")  # noqa: E501

        self._change_invoice_address = change_invoice_address
