# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_change_contact_information_change_contact_information import AllOfChangeContactInformationChangeContactInformation  # noqa: F401,E501
from ods_api_server import util


class ChangeContactInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_contact_information: AllOfChangeContactInformationChangeContactInformation=None):  # noqa: E501
        """ChangeContactInformation - a model defined in Swagger

        :param change_contact_information: The change_contact_information of this ChangeContactInformation.  # noqa: E501
        :type change_contact_information: AllOfChangeContactInformationChangeContactInformation
        """
        self.swagger_types = {
            'change_contact_information': AllOfChangeContactInformationChangeContactInformation
        }

        self.attribute_map = {
            'change_contact_information': 'ChangeContactInformation'
        }
        self._change_contact_information = change_contact_information

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeContactInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeContactInformation of this ChangeContactInformation.  # noqa: E501
        :rtype: ChangeContactInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_contact_information(self) -> AllOfChangeContactInformationChangeContactInformation:
        """Gets the change_contact_information of this ChangeContactInformation.


        :return: The change_contact_information of this ChangeContactInformation.
        :rtype: AllOfChangeContactInformationChangeContactInformation
        """
        return self._change_contact_information

    @change_contact_information.setter
    def change_contact_information(self, change_contact_information: AllOfChangeContactInformationChangeContactInformation):
        """Sets the change_contact_information of this ChangeContactInformation.


        :param change_contact_information: The change_contact_information of this ChangeContactInformation.
        :type change_contact_information: AllOfChangeContactInformationChangeContactInformation
        """
        if change_contact_information is None:
            raise ValueError("Invalid value for `change_contact_information`, must not be `None`")  # noqa: E501

        self._change_contact_information = change_contact_information
