# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_customer_address_v2 import ChangeCustomerAddressV2  # noqa: F401,E501
from ods_api_server import util


class ChangeCustomerAddressV2Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_customer_address_v2: object=None):  # noqa: E501
        """ChangeCustomerAddressV2Body - a model defined in Swagger

        :param change_customer_address_v2: The change_customer_address_v2 of this ChangeCustomerAddressV2Body.  # noqa: E501
        :type change_customer_address_v2: object
        """
        self.swagger_types = {
            'change_customer_address_v2': object
        }

        self.attribute_map = {
            'change_customer_address_v2': 'ChangeCustomerAddressV2'
        }
        self._change_customer_address_v2 = change_customer_address_v2

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeCustomerAddressV2Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeCustomerAddressV2_body of this ChangeCustomerAddressV2Body.  # noqa: E501
        :rtype: ChangeCustomerAddressV2Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_customer_address_v2(self) -> object:
        """Gets the change_customer_address_v2 of this ChangeCustomerAddressV2Body.


        :return: The change_customer_address_v2 of this ChangeCustomerAddressV2Body.
        :rtype: object
        """
        return self._change_customer_address_v2

    @change_customer_address_v2.setter
    def change_customer_address_v2(self, change_customer_address_v2: object):
        """Sets the change_customer_address_v2 of this ChangeCustomerAddressV2Body.


        :param change_customer_address_v2: The change_customer_address_v2 of this ChangeCustomerAddressV2Body.
        :type change_customer_address_v2: object
        """
        if change_customer_address_v2 is None:
            raise ValueError("Invalid value for `change_customer_address_v2`, must not be `None`")  # noqa: E501

        self._change_customer_address_v2 = change_customer_address_v2
