# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_customer_address import ChangeCustomerAddress  # noqa: F401,E501
from ods_api_server import util


class ChangeCustomerAddressBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_customer_address: object=None):  # noqa: E501
        """ChangeCustomerAddressBody - a model defined in Swagger

        :param change_customer_address: The change_customer_address of this ChangeCustomerAddressBody.  # noqa: E501
        :type change_customer_address: object
        """
        self.swagger_types = {
            'change_customer_address': object
        }

        self.attribute_map = {
            'change_customer_address': 'ChangeCustomerAddress'
        }
        self._change_customer_address = change_customer_address

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeCustomerAddressBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeCustomerAddress_body of this ChangeCustomerAddressBody.  # noqa: E501
        :rtype: ChangeCustomerAddressBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_customer_address(self) -> object:
        """Gets the change_customer_address of this ChangeCustomerAddressBody.


        :return: The change_customer_address of this ChangeCustomerAddressBody.
        :rtype: object
        """
        return self._change_customer_address

    @change_customer_address.setter
    def change_customer_address(self, change_customer_address: object):
        """Sets the change_customer_address of this ChangeCustomerAddressBody.


        :param change_customer_address: The change_customer_address of this ChangeCustomerAddressBody.
        :type change_customer_address: object
        """
        if change_customer_address is None:
            raise ValueError("Invalid value for `change_customer_address`, must not be `None`")  # noqa: E501

        self._change_customer_address = change_customer_address
