# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_contact_information import ChangeContactInformation  # noqa: F401,E501
from ods_api_server import util


class ChangeContactInformationBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_contact_information: object=None):  # noqa: E501
        """ChangeContactInformationBody - a model defined in Swagger

        :param change_contact_information: The change_contact_information of this ChangeContactInformationBody.  # noqa: E501
        :type change_contact_information: object
        """
        self.swagger_types = {
            'change_contact_information': object
        }

        self.attribute_map = {
            'change_contact_information': 'ChangeContactInformation'
        }
        self._change_contact_information = change_contact_information

    @classmethod
    def from_dict(cls, dikt) -> 'ChangeContactInformationBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChangeContactInformation_body of this ChangeContactInformationBody.  # noqa: E501
        :rtype: ChangeContactInformationBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_contact_information(self) -> object:
        """Gets the change_contact_information of this ChangeContactInformationBody.


        :return: The change_contact_information of this ChangeContactInformationBody.
        :rtype: object
        """
        return self._change_contact_information

    @change_contact_information.setter
    def change_contact_information(self, change_contact_information: object):
        """Sets the change_contact_information of this ChangeContactInformationBody.


        :param change_contact_information: The change_contact_information of this ChangeContactInformationBody.
        :type change_contact_information: object
        """
        if change_contact_information is None:
            raise ValueError("Invalid value for `change_contact_information`, must not be `None`")  # noqa: E501

        self._change_contact_information = change_contact_information
