# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_confirm_invoice_confirm_invoice import AllOfConfirmInvoiceConfirmInvoice  # noqa: F401,E501
from ods_api_server import util


class ConfirmInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, confirm_invoice: AllOfConfirmInvoiceConfirmInvoice=None):  # noqa: E501
        """ConfirmInvoice - a model defined in Swagger

        :param confirm_invoice: The confirm_invoice of this ConfirmInvoice.  # noqa: E501
        :type confirm_invoice: AllOfConfirmInvoiceConfirmInvoice
        """
        self.swagger_types = {
            'confirm_invoice': AllOfConfirmInvoiceConfirmInvoice
        }

        self.attribute_map = {
            'confirm_invoice': 'ConfirmInvoice'
        }
        self._confirm_invoice = confirm_invoice

    @classmethod
    def from_dict(cls, dikt) -> 'ConfirmInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfirmInvoice of this ConfirmInvoice.  # noqa: E501
        :rtype: ConfirmInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def confirm_invoice(self) -> AllOfConfirmInvoiceConfirmInvoice:
        """Gets the confirm_invoice of this ConfirmInvoice.


        :return: The confirm_invoice of this ConfirmInvoice.
        :rtype: AllOfConfirmInvoiceConfirmInvoice
        """
        return self._confirm_invoice

    @confirm_invoice.setter
    def confirm_invoice(self, confirm_invoice: AllOfConfirmInvoiceConfirmInvoice):
        """Sets the confirm_invoice of this ConfirmInvoice.


        :param confirm_invoice: The confirm_invoice of this ConfirmInvoice.
        :type confirm_invoice: AllOfConfirmInvoiceConfirmInvoice
        """
        if confirm_invoice is None:
            raise ValueError("Invalid value for `confirm_invoice`, must not be `None`")  # noqa: E501

        self._confirm_invoice = confirm_invoice
