# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_v3_result import ModifyInvoiceV3Result  # noqa: F401,E501
from ods_api_server import util


class InlineResponse2008(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v3_result: object=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger

        :param modify_invoice_v3_result: The modify_invoice_v3_result of this InlineResponse2008.  # noqa: E501
        :type modify_invoice_v3_result: object
        """
        self.swagger_types = {
            'modify_invoice_v3_result': object
        }

        self.attribute_map = {
            'modify_invoice_v3_result': 'ModifyInvoiceV3_Result'
        }
        self._modify_invoice_v3_result = modify_invoice_v3_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8 of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v3_result(self) -> object:
        """Gets the modify_invoice_v3_result of this InlineResponse2008.


        :return: The modify_invoice_v3_result of this InlineResponse2008.
        :rtype: object
        """
        return self._modify_invoice_v3_result

    @modify_invoice_v3_result.setter
    def modify_invoice_v3_result(self, modify_invoice_v3_result: object):
        """Sets the modify_invoice_v3_result of this InlineResponse2008.


        :param modify_invoice_v3_result: The modify_invoice_v3_result of this InlineResponse2008.
        :type modify_invoice_v3_result: object
        """
        if modify_invoice_v3_result is None:
            raise ValueError("Invalid value for `modify_invoice_v3_result`, must not be `None`")  # noqa: E501

        self._modify_invoice_v3_result = modify_invoice_v3_result
