# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_invoice_address_result import ChangeInvoiceAddressResult  # noqa: F401,E501
from ods_api_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_invoice_address_result: object=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param change_invoice_address_result: The change_invoice_address_result of this InlineResponse200.  # noqa: E501
        :type change_invoice_address_result: object
        """
        self.swagger_types = {
            'change_invoice_address_result': object
        }

        self.attribute_map = {
            'change_invoice_address_result': 'ChangeInvoiceAddress_Result'
        }
        self._change_invoice_address_result = change_invoice_address_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_invoice_address_result(self) -> object:
        """Gets the change_invoice_address_result of this InlineResponse200.


        :return: The change_invoice_address_result of this InlineResponse200.
        :rtype: object
        """
        return self._change_invoice_address_result

    @change_invoice_address_result.setter
    def change_invoice_address_result(self, change_invoice_address_result: object):
        """Sets the change_invoice_address_result of this InlineResponse200.


        :param change_invoice_address_result: The change_invoice_address_result of this InlineResponse200.
        :type change_invoice_address_result: object
        """
        if change_invoice_address_result is None:
            raise ValueError("Invalid value for `change_invoice_address_result`, must not be `None`")  # noqa: E501

        self._change_invoice_address_result = change_invoice_address_result
