# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_result import ModifyInvoiceResult  # noqa: F401,E501
from ods_api_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_result: object=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param modify_invoice_result: The modify_invoice_result of this InlineResponse2004.  # noqa: E501
        :type modify_invoice_result: object
        """
        self.swagger_types = {
            'modify_invoice_result': object
        }

        self.attribute_map = {
            'modify_invoice_result': 'ModifyInvoice_Result'
        }
        self._modify_invoice_result = modify_invoice_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_result(self) -> object:
        """Gets the modify_invoice_result of this InlineResponse2004.


        :return: The modify_invoice_result of this InlineResponse2004.
        :rtype: object
        """
        return self._modify_invoice_result

    @modify_invoice_result.setter
    def modify_invoice_result(self, modify_invoice_result: object):
        """Sets the modify_invoice_result of this InlineResponse2004.


        :param modify_invoice_result: The modify_invoice_result of this InlineResponse2004.
        :type modify_invoice_result: object
        """
        if modify_invoice_result is None:
            raise ValueError("Invalid value for `modify_invoice_result`, must not be `None`")  # noqa: E501

        self._modify_invoice_result = modify_invoice_result
