# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_v4_result import ModifyInvoiceV4Result  # noqa: F401,E501
from ods_api_server import util


class InlineResponse20010(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v4_result: object=None):  # noqa: E501
        """InlineResponse20010 - a model defined in Swagger

        :param modify_invoice_v4_result: The modify_invoice_v4_result of this InlineResponse20010.  # noqa: E501
        :type modify_invoice_v4_result: object
        """
        self.swagger_types = {
            'modify_invoice_v4_result': object
        }

        self.attribute_map = {
            'modify_invoice_v4_result': 'ModifyInvoiceV4_Result'
        }
        self._modify_invoice_v4_result = modify_invoice_v4_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10 of this InlineResponse20010.  # noqa: E501
        :rtype: InlineResponse20010
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v4_result(self) -> object:
        """Gets the modify_invoice_v4_result of this InlineResponse20010.


        :return: The modify_invoice_v4_result of this InlineResponse20010.
        :rtype: object
        """
        return self._modify_invoice_v4_result

    @modify_invoice_v4_result.setter
    def modify_invoice_v4_result(self, modify_invoice_v4_result: object):
        """Sets the modify_invoice_v4_result of this InlineResponse20010.


        :param modify_invoice_v4_result: The modify_invoice_v4_result of this InlineResponse20010.
        :type modify_invoice_v4_result: object
        """
        if modify_invoice_v4_result is None:
            raise ValueError("Invalid value for `modify_invoice_v4_result`, must not be `None`")  # noqa: E501

        self._modify_invoice_v4_result = modify_invoice_v4_result
