# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_contact_information_result import ChangeContactInformationResult  # noqa: F401,E501
from ods_api_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_contact_information_result: object=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param change_contact_information_result: The change_contact_information_result of this InlineResponse2002.  # noqa: E501
        :type change_contact_information_result: object
        """
        self.swagger_types = {
            'change_contact_information_result': object
        }

        self.attribute_map = {
            'change_contact_information_result': 'ChangeContactInformation_Result'
        }
        self._change_contact_information_result = change_contact_information_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_contact_information_result(self) -> object:
        """Gets the change_contact_information_result of this InlineResponse2002.


        :return: The change_contact_information_result of this InlineResponse2002.
        :rtype: object
        """
        return self._change_contact_information_result

    @change_contact_information_result.setter
    def change_contact_information_result(self, change_contact_information_result: object):
        """Sets the change_contact_information_result of this InlineResponse2002.


        :param change_contact_information_result: The change_contact_information_result of this InlineResponse2002.
        :type change_contact_information_result: object
        """
        if change_contact_information_result is None:
            raise ValueError("Invalid value for `change_contact_information_result`, must not be `None`")  # noqa: E501

        self._change_contact_information_result = change_contact_information_result
