# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_hotel_bank_account_info_result import ModifyHotelBankAccountInfoResult  # noqa: F401,E501
from ods_api_server import util


class InlineResponse20013(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_hotel_bank_account_info_result: object=None):  # noqa: E501
        """InlineResponse20013 - a model defined in Swagger

        :param modify_hotel_bank_account_info_result: The modify_hotel_bank_account_info_result of this InlineResponse20013.  # noqa: E501
        :type modify_hotel_bank_account_info_result: object
        """
        self.swagger_types = {
            'modify_hotel_bank_account_info_result': object
        }

        self.attribute_map = {
            'modify_hotel_bank_account_info_result': 'ModifyHotelBankAccountInfo_Result'
        }
        self._modify_hotel_bank_account_info_result = modify_hotel_bank_account_info_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20013':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_13 of this InlineResponse20013.  # noqa: E501
        :rtype: InlineResponse20013
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_hotel_bank_account_info_result(self) -> object:
        """Gets the modify_hotel_bank_account_info_result of this InlineResponse20013.


        :return: The modify_hotel_bank_account_info_result of this InlineResponse20013.
        :rtype: object
        """
        return self._modify_hotel_bank_account_info_result

    @modify_hotel_bank_account_info_result.setter
    def modify_hotel_bank_account_info_result(self, modify_hotel_bank_account_info_result: object):
        """Sets the modify_hotel_bank_account_info_result of this InlineResponse20013.


        :param modify_hotel_bank_account_info_result: The modify_hotel_bank_account_info_result of this InlineResponse20013.
        :type modify_hotel_bank_account_info_result: object
        """
        if modify_hotel_bank_account_info_result is None:
            raise ValueError("Invalid value for `modify_hotel_bank_account_info_result`, must not be `None`")  # noqa: E501

        self._modify_hotel_bank_account_info_result = modify_hotel_bank_account_info_result
