# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.change_customer_address_v2_result import ChangeCustomerAddressV2Result  # noqa: F401,E501
from ods_api_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, change_customer_address_v2_result: object=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param change_customer_address_v2_result: The change_customer_address_v2_result of this InlineResponse2006.  # noqa: E501
        :type change_customer_address_v2_result: object
        """
        self.swagger_types = {
            'change_customer_address_v2_result': object
        }

        self.attribute_map = {
            'change_customer_address_v2_result': 'ChangeCustomerAddressV2_Result'
        }
        self._change_customer_address_v2_result = change_customer_address_v2_result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def change_customer_address_v2_result(self) -> object:
        """Gets the change_customer_address_v2_result of this InlineResponse2006.


        :return: The change_customer_address_v2_result of this InlineResponse2006.
        :rtype: object
        """
        return self._change_customer_address_v2_result

    @change_customer_address_v2_result.setter
    def change_customer_address_v2_result(self, change_customer_address_v2_result: object):
        """Sets the change_customer_address_v2_result of this InlineResponse2006.


        :param change_customer_address_v2_result: The change_customer_address_v2_result of this InlineResponse2006.
        :type change_customer_address_v2_result: object
        """
        if change_customer_address_v2_result is None:
            raise ValueError("Invalid value for `change_customer_address_v2_result`, must not be `None`")  # noqa: E501

        self._change_customer_address_v2_result = change_customer_address_v2_result
