# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_insert_payment_v2_insert_payment_v2 import AllOfInsertPaymentV2InsertPaymentV2  # noqa: F401,E501
from ods_api_server import util


class InsertPaymentV2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment_v2: AllOfInsertPaymentV2InsertPaymentV2=None):  # noqa: E501
        """InsertPaymentV2 - a model defined in Swagger

        :param insert_payment_v2: The insert_payment_v2 of this InsertPaymentV2.  # noqa: E501
        :type insert_payment_v2: AllOfInsertPaymentV2InsertPaymentV2
        """
        self.swagger_types = {
            'insert_payment_v2': AllOfInsertPaymentV2InsertPaymentV2
        }

        self.attribute_map = {
            'insert_payment_v2': 'InsertPaymentV2'
        }
        self._insert_payment_v2 = insert_payment_v2

    @classmethod
    def from_dict(cls, dikt) -> 'InsertPaymentV2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InsertPaymentV2 of this InsertPaymentV2.  # noqa: E501
        :rtype: InsertPaymentV2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment_v2(self) -> AllOfInsertPaymentV2InsertPaymentV2:
        """Gets the insert_payment_v2 of this InsertPaymentV2.


        :return: The insert_payment_v2 of this InsertPaymentV2.
        :rtype: AllOfInsertPaymentV2InsertPaymentV2
        """
        return self._insert_payment_v2

    @insert_payment_v2.setter
    def insert_payment_v2(self, insert_payment_v2: AllOfInsertPaymentV2InsertPaymentV2):
        """Sets the insert_payment_v2 of this InsertPaymentV2.


        :param insert_payment_v2: The insert_payment_v2 of this InsertPaymentV2.
        :type insert_payment_v2: AllOfInsertPaymentV2InsertPaymentV2
        """
        if insert_payment_v2 is None:
            raise ValueError("Invalid value for `insert_payment_v2`, must not be `None`")  # noqa: E501

        self._insert_payment_v2 = insert_payment_v2
