# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_insert_payment_v3_insert_payment_v3 import AllOfInsertPaymentV3InsertPaymentV3  # noqa: F401,E501
from ods_api_server import util


class InsertPaymentV3(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment_v3: AllOfInsertPaymentV3InsertPaymentV3=None):  # noqa: E501
        """InsertPaymentV3 - a model defined in Swagger

        :param insert_payment_v3: The insert_payment_v3 of this InsertPaymentV3.  # noqa: E501
        :type insert_payment_v3: AllOfInsertPaymentV3InsertPaymentV3
        """
        self.swagger_types = {
            'insert_payment_v3': AllOfInsertPaymentV3InsertPaymentV3
        }

        self.attribute_map = {
            'insert_payment_v3': 'InsertPaymentV3'
        }
        self._insert_payment_v3 = insert_payment_v3

    @classmethod
    def from_dict(cls, dikt) -> 'InsertPaymentV3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InsertPaymentV3 of this InsertPaymentV3.  # noqa: E501
        :rtype: InsertPaymentV3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment_v3(self) -> AllOfInsertPaymentV3InsertPaymentV3:
        """Gets the insert_payment_v3 of this InsertPaymentV3.


        :return: The insert_payment_v3 of this InsertPaymentV3.
        :rtype: AllOfInsertPaymentV3InsertPaymentV3
        """
        return self._insert_payment_v3

    @insert_payment_v3.setter
    def insert_payment_v3(self, insert_payment_v3: AllOfInsertPaymentV3InsertPaymentV3):
        """Sets the insert_payment_v3 of this InsertPaymentV3.


        :param insert_payment_v3: The insert_payment_v3 of this InsertPaymentV3.
        :type insert_payment_v3: AllOfInsertPaymentV3InsertPaymentV3
        """
        if insert_payment_v3 is None:
            raise ValueError("Invalid value for `insert_payment_v3`, must not be `None`")  # noqa: E501

        self._insert_payment_v3 = insert_payment_v3
