# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.insert_payment_pc import InsertPaymentPC  # noqa: F401,E501
from ods_api_server import util


class InsertPaymentPCBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment_pc: object=None):  # noqa: E501
        """InsertPaymentPCBody - a model defined in Swagger

        :param insert_payment_pc: The insert_payment_pc of this InsertPaymentPCBody.  # noqa: E501
        :type insert_payment_pc: object
        """
        self.swagger_types = {
            'insert_payment_pc': object
        }

        self.attribute_map = {
            'insert_payment_pc': 'InsertPaymentPC'
        }
        self._insert_payment_pc = insert_payment_pc

    @classmethod
    def from_dict(cls, dikt) -> 'InsertPaymentPCBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InsertPaymentPC_body of this InsertPaymentPCBody.  # noqa: E501
        :rtype: InsertPaymentPCBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment_pc(self) -> object:
        """Gets the insert_payment_pc of this InsertPaymentPCBody.


        :return: The insert_payment_pc of this InsertPaymentPCBody.
        :rtype: object
        """
        return self._insert_payment_pc

    @insert_payment_pc.setter
    def insert_payment_pc(self, insert_payment_pc: object):
        """Sets the insert_payment_pc of this InsertPaymentPCBody.


        :param insert_payment_pc: The insert_payment_pc of this InsertPaymentPCBody.
        :type insert_payment_pc: object
        """
        if insert_payment_pc is None:
            raise ValueError("Invalid value for `insert_payment_pc`, must not be `None`")  # noqa: E501

        self._insert_payment_pc = insert_payment_pc
