# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.insert_payment_v2 import InsertPaymentV2  # noqa: F401,E501
from ods_api_server import util


class InsertPaymentV2Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment_v2: object=None):  # noqa: E501
        """InsertPaymentV2Body - a model defined in Swagger

        :param insert_payment_v2: The insert_payment_v2 of this InsertPaymentV2Body.  # noqa: E501
        :type insert_payment_v2: object
        """
        self.swagger_types = {
            'insert_payment_v2': object
        }

        self.attribute_map = {
            'insert_payment_v2': 'InsertPaymentV2'
        }
        self._insert_payment_v2 = insert_payment_v2

    @classmethod
    def from_dict(cls, dikt) -> 'InsertPaymentV2Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InsertPaymentV2_body of this InsertPaymentV2Body.  # noqa: E501
        :rtype: InsertPaymentV2Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment_v2(self) -> object:
        """Gets the insert_payment_v2 of this InsertPaymentV2Body.


        :return: The insert_payment_v2 of this InsertPaymentV2Body.
        :rtype: object
        """
        return self._insert_payment_v2

    @insert_payment_v2.setter
    def insert_payment_v2(self, insert_payment_v2: object):
        """Sets the insert_payment_v2 of this InsertPaymentV2Body.


        :param insert_payment_v2: The insert_payment_v2 of this InsertPaymentV2Body.
        :type insert_payment_v2: object
        """
        if insert_payment_v2 is None:
            raise ValueError("Invalid value for `insert_payment_v2`, must not be `None`")  # noqa: E501

        self._insert_payment_v2 = insert_payment_v2
