# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_modify_hotel_credit_card_info_modify_hotel_credit_card_info import AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo  # noqa: F401,E501
from ods_api_server import util


class ModifyHotelCreditCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_hotel_credit_card_info: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo=None):  # noqa: E501
        """ModifyHotelCreditCardInfo - a model defined in Swagger

        :param modify_hotel_credit_card_info: The modify_hotel_credit_card_info of this ModifyHotelCreditCardInfo.  # noqa: E501
        :type modify_hotel_credit_card_info: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo
        """
        self.swagger_types = {
            'modify_hotel_credit_card_info': AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo
        }

        self.attribute_map = {
            'modify_hotel_credit_card_info': 'ModifyHotelCreditCardInfo'
        }
        self._modify_hotel_credit_card_info = modify_hotel_credit_card_info

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyHotelCreditCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyHotelCreditCardInfo of this ModifyHotelCreditCardInfo.  # noqa: E501
        :rtype: ModifyHotelCreditCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_hotel_credit_card_info(self) -> AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo:
        """Gets the modify_hotel_credit_card_info of this ModifyHotelCreditCardInfo.


        :return: The modify_hotel_credit_card_info of this ModifyHotelCreditCardInfo.
        :rtype: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo
        """
        return self._modify_hotel_credit_card_info

    @modify_hotel_credit_card_info.setter
    def modify_hotel_credit_card_info(self, modify_hotel_credit_card_info: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo):
        """Sets the modify_hotel_credit_card_info of this ModifyHotelCreditCardInfo.


        :param modify_hotel_credit_card_info: The modify_hotel_credit_card_info of this ModifyHotelCreditCardInfo.
        :type modify_hotel_credit_card_info: AllOfModifyHotelCreditCardInfoModifyHotelCreditCardInfo
        """
        if modify_hotel_credit_card_info is None:
            raise ValueError("Invalid value for `modify_hotel_credit_card_info`, must not be `None`")  # noqa: E501

        self._modify_hotel_credit_card_info = modify_hotel_credit_card_info
