# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_v2 import ModifyInvoiceV2  # noqa: F401,E501
from ods_api_server import util


class ModifyInvoiceV2Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v2: object=None):  # noqa: E501
        """ModifyInvoiceV2Body - a model defined in Swagger

        :param modify_invoice_v2: The modify_invoice_v2 of this ModifyInvoiceV2Body.  # noqa: E501
        :type modify_invoice_v2: object
        """
        self.swagger_types = {
            'modify_invoice_v2': object
        }

        self.attribute_map = {
            'modify_invoice_v2': 'ModifyInvoiceV2'
        }
        self._modify_invoice_v2 = modify_invoice_v2

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyInvoiceV2Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyInvoiceV2_body of this ModifyInvoiceV2Body.  # noqa: E501
        :rtype: ModifyInvoiceV2Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v2(self) -> object:
        """Gets the modify_invoice_v2 of this ModifyInvoiceV2Body.


        :return: The modify_invoice_v2 of this ModifyInvoiceV2Body.
        :rtype: object
        """
        return self._modify_invoice_v2

    @modify_invoice_v2.setter
    def modify_invoice_v2(self, modify_invoice_v2: object):
        """Sets the modify_invoice_v2 of this ModifyInvoiceV2Body.


        :param modify_invoice_v2: The modify_invoice_v2 of this ModifyInvoiceV2Body.
        :type modify_invoice_v2: object
        """
        if modify_invoice_v2 is None:
            raise ValueError("Invalid value for `modify_invoice_v2`, must not be `None`")  # noqa: E501

        self._modify_invoice_v2 = modify_invoice_v2
