# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_modify_invoice_v2_modify_invoice_v2 import AllOfModifyInvoiceV2ModifyInvoiceV2  # noqa: F401,E501
from ods_api_server import util


class ModifyInvoiceV2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v2: AllOfModifyInvoiceV2ModifyInvoiceV2=None):  # noqa: E501
        """ModifyInvoiceV2 - a model defined in Swagger

        :param modify_invoice_v2: The modify_invoice_v2 of this ModifyInvoiceV2.  # noqa: E501
        :type modify_invoice_v2: AllOfModifyInvoiceV2ModifyInvoiceV2
        """
        self.swagger_types = {
            'modify_invoice_v2': AllOfModifyInvoiceV2ModifyInvoiceV2
        }

        self.attribute_map = {
            'modify_invoice_v2': 'ModifyInvoiceV2'
        }
        self._modify_invoice_v2 = modify_invoice_v2

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyInvoiceV2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyInvoiceV2 of this ModifyInvoiceV2.  # noqa: E501
        :rtype: ModifyInvoiceV2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v2(self) -> AllOfModifyInvoiceV2ModifyInvoiceV2:
        """Gets the modify_invoice_v2 of this ModifyInvoiceV2.


        :return: The modify_invoice_v2 of this ModifyInvoiceV2.
        :rtype: AllOfModifyInvoiceV2ModifyInvoiceV2
        """
        return self._modify_invoice_v2

    @modify_invoice_v2.setter
    def modify_invoice_v2(self, modify_invoice_v2: AllOfModifyInvoiceV2ModifyInvoiceV2):
        """Sets the modify_invoice_v2 of this ModifyInvoiceV2.


        :param modify_invoice_v2: The modify_invoice_v2 of this ModifyInvoiceV2.
        :type modify_invoice_v2: AllOfModifyInvoiceV2ModifyInvoiceV2
        """
        if modify_invoice_v2 is None:
            raise ValueError("Invalid value for `modify_invoice_v2`, must not be `None`")  # noqa: E501

        self._modify_invoice_v2 = modify_invoice_v2
