# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_of_modify_invoice_modify_invoice import AllOfModifyInvoiceModifyInvoice  # noqa: F401,E501
from ods_api_server import util


class ModifyInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice: AllOfModifyInvoiceModifyInvoice=None):  # noqa: E501
        """ModifyInvoice - a model defined in Swagger

        :param modify_invoice: The modify_invoice of this ModifyInvoice.  # noqa: E501
        :type modify_invoice: AllOfModifyInvoiceModifyInvoice
        """
        self.swagger_types = {
            'modify_invoice': AllOfModifyInvoiceModifyInvoice
        }

        self.attribute_map = {
            'modify_invoice': 'ModifyInvoice'
        }
        self._modify_invoice = modify_invoice

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyInvoice of this ModifyInvoice.  # noqa: E501
        :rtype: ModifyInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice(self) -> AllOfModifyInvoiceModifyInvoice:
        """Gets the modify_invoice of this ModifyInvoice.


        :return: The modify_invoice of this ModifyInvoice.
        :rtype: AllOfModifyInvoiceModifyInvoice
        """
        return self._modify_invoice

    @modify_invoice.setter
    def modify_invoice(self, modify_invoice: AllOfModifyInvoiceModifyInvoice):
        """Sets the modify_invoice of this ModifyInvoice.


        :param modify_invoice: The modify_invoice of this ModifyInvoice.
        :type modify_invoice: AllOfModifyInvoiceModifyInvoice
        """
        if modify_invoice is None:
            raise ValueError("Invalid value for `modify_invoice`, must not be `None`")  # noqa: E501

        self._modify_invoice = modify_invoice
