# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_v3 import ModifyInvoiceV3  # noqa: F401,E501
from ods_api_server import util


class ModifyInvoiceV3Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v3: object=None):  # noqa: E501
        """ModifyInvoiceV3Body - a model defined in Swagger

        :param modify_invoice_v3: The modify_invoice_v3 of this ModifyInvoiceV3Body.  # noqa: E501
        :type modify_invoice_v3: object
        """
        self.swagger_types = {
            'modify_invoice_v3': object
        }

        self.attribute_map = {
            'modify_invoice_v3': 'ModifyInvoiceV3'
        }
        self._modify_invoice_v3 = modify_invoice_v3

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyInvoiceV3Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyInvoiceV3_body of this ModifyInvoiceV3Body.  # noqa: E501
        :rtype: ModifyInvoiceV3Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v3(self) -> object:
        """Gets the modify_invoice_v3 of this ModifyInvoiceV3Body.


        :return: The modify_invoice_v3 of this ModifyInvoiceV3Body.
        :rtype: object
        """
        return self._modify_invoice_v3

    @modify_invoice_v3.setter
    def modify_invoice_v3(self, modify_invoice_v3: object):
        """Sets the modify_invoice_v3 of this ModifyInvoiceV3Body.


        :param modify_invoice_v3: The modify_invoice_v3 of this ModifyInvoiceV3Body.
        :type modify_invoice_v3: object
        """
        if modify_invoice_v3 is None:
            raise ValueError("Invalid value for `modify_invoice_v3`, must not be `None`")  # noqa: E501

        self._modify_invoice_v3 = modify_invoice_v3
