# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.modify_invoice_v4 import ModifyInvoiceV4  # noqa: F401,E501
from ods_api_server import util


class ModifyInvoiceV4Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice_v4: object=None):  # noqa: E501
        """ModifyInvoiceV4Body - a model defined in Swagger

        :param modify_invoice_v4: The modify_invoice_v4 of this ModifyInvoiceV4Body.  # noqa: E501
        :type modify_invoice_v4: object
        """
        self.swagger_types = {
            'modify_invoice_v4': object
        }

        self.attribute_map = {
            'modify_invoice_v4': 'ModifyInvoiceV4'
        }
        self._modify_invoice_v4 = modify_invoice_v4

    @classmethod
    def from_dict(cls, dikt) -> 'ModifyInvoiceV4Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModifyInvoiceV4_body of this ModifyInvoiceV4Body.  # noqa: E501
        :rtype: ModifyInvoiceV4Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice_v4(self) -> object:
        """Gets the modify_invoice_v4 of this ModifyInvoiceV4Body.


        :return: The modify_invoice_v4 of this ModifyInvoiceV4Body.
        :rtype: object
        """
        return self._modify_invoice_v4

    @modify_invoice_v4.setter
    def modify_invoice_v4(self, modify_invoice_v4: object):
        """Sets the modify_invoice_v4 of this ModifyInvoiceV4Body.


        :param modify_invoice_v4: The modify_invoice_v4 of this ModifyInvoiceV4Body.
        :type modify_invoice_v4: object
        """
        if modify_invoice_v4 is None:
            raise ValueError("Invalid value for `modify_invoice_v4`, must not be `None`")  # noqa: E501

        self._modify_invoice_v4 = modify_invoice_v4
