# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q10_invoice import Q10Invoice  # noqa: F401,E501
from ods_api_server import util


class Q10InvoiceList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice: List[Q10Invoice]=None):  # noqa: E501
        """Q10InvoiceList - a model defined in Swagger

        :param invoice: The invoice of this Q10InvoiceList.  # noqa: E501
        :type invoice: List[Q10Invoice]
        """
        self.swagger_types = {
            'invoice': List[Q10Invoice]
        }

        self.attribute_map = {
            'invoice': 'Invoice'
        }
        self._invoice = invoice

    @classmethod
    def from_dict(cls, dikt) -> 'Q10InvoiceList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q10_InvoiceList of this Q10InvoiceList.  # noqa: E501
        :rtype: Q10InvoiceList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice(self) -> List[Q10Invoice]:
        """Gets the invoice of this Q10InvoiceList.


        :return: The invoice of this Q10InvoiceList.
        :rtype: List[Q10Invoice]
        """
        return self._invoice

    @invoice.setter
    def invoice(self, invoice: List[Q10Invoice]):
        """Sets the invoice of this Q10InvoiceList.


        :param invoice: The invoice of this Q10InvoiceList.
        :type invoice: List[Q10Invoice]
        """
        if invoice is None:
            raise ValueError("Invalid value for `invoice`, must not be `None`")  # noqa: E501

        self._invoice = invoice
