# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q22_positions import Q22Positions  # noqa: F401,E501
from ods_api_server.models.all_ofq22_invoice_invoice_address import AllOfq22InvoiceInvoiceAddress  # noqa: F401,E501
from ods_api_server import util


class Q22Invoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, doc_no: str=None, is_cancelled: str=None, invoice_address: AllOfq22InvoiceInvoiceAddress=None, positions: List[Q22Positions]=None):  # noqa: E501
        """Q22Invoice - a model defined in Swagger

        :param doc_no: The doc_no of this Q22Invoice.  # noqa: E501
        :type doc_no: str
        :param is_cancelled: The is_cancelled of this Q22Invoice.  # noqa: E501
        :type is_cancelled: str
        :param invoice_address: The invoice_address of this Q22Invoice.  # noqa: E501
        :type invoice_address: AllOfq22InvoiceInvoiceAddress
        :param positions: The positions of this Q22Invoice.  # noqa: E501
        :type positions: List[Q22Positions]
        """
        self.swagger_types = {
            'doc_no': str,
            'is_cancelled': str,
            'invoice_address': AllOfq22InvoiceInvoiceAddress,
            'positions': List[Q22Positions]
        }

        self.attribute_map = {
            'doc_no': 'DocNo',
            'is_cancelled': 'IsCancelled',
            'invoice_address': 'InvoiceAddress',
            'positions': 'Positions'
        }
        self._doc_no = doc_no
        self._is_cancelled = is_cancelled
        self._invoice_address = invoice_address
        self._positions = positions

    @classmethod
    def from_dict(cls, dikt) -> 'Q22Invoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q22_Invoice of this Q22Invoice.  # noqa: E501
        :rtype: Q22Invoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def doc_no(self) -> str:
        """Gets the doc_no of this Q22Invoice.


        :return: The doc_no of this Q22Invoice.
        :rtype: str
        """
        return self._doc_no

    @doc_no.setter
    def doc_no(self, doc_no: str):
        """Sets the doc_no of this Q22Invoice.


        :param doc_no: The doc_no of this Q22Invoice.
        :type doc_no: str
        """
        if doc_no is None:
            raise ValueError("Invalid value for `doc_no`, must not be `None`")  # noqa: E501

        self._doc_no = doc_no

    @property
    def is_cancelled(self) -> str:
        """Gets the is_cancelled of this Q22Invoice.


        :return: The is_cancelled of this Q22Invoice.
        :rtype: str
        """
        return self._is_cancelled

    @is_cancelled.setter
    def is_cancelled(self, is_cancelled: str):
        """Sets the is_cancelled of this Q22Invoice.


        :param is_cancelled: The is_cancelled of this Q22Invoice.
        :type is_cancelled: str
        """
        if is_cancelled is None:
            raise ValueError("Invalid value for `is_cancelled`, must not be `None`")  # noqa: E501

        self._is_cancelled = is_cancelled

    @property
    def invoice_address(self) -> AllOfq22InvoiceInvoiceAddress:
        """Gets the invoice_address of this Q22Invoice.


        :return: The invoice_address of this Q22Invoice.
        :rtype: AllOfq22InvoiceInvoiceAddress
        """
        return self._invoice_address

    @invoice_address.setter
    def invoice_address(self, invoice_address: AllOfq22InvoiceInvoiceAddress):
        """Sets the invoice_address of this Q22Invoice.


        :param invoice_address: The invoice_address of this Q22Invoice.
        :type invoice_address: AllOfq22InvoiceInvoiceAddress
        """
        if invoice_address is None:
            raise ValueError("Invalid value for `invoice_address`, must not be `None`")  # noqa: E501

        self._invoice_address = invoice_address

    @property
    def positions(self) -> List[Q22Positions]:
        """Gets the positions of this Q22Invoice.


        :return: The positions of this Q22Invoice.
        :rtype: List[Q22Positions]
        """
        return self._positions

    @positions.setter
    def positions(self, positions: List[Q22Positions]):
        """Sets the positions of this Q22Invoice.


        :param positions: The positions of this Q22Invoice.
        :type positions: List[Q22Positions]
        """
        if positions is None:
            raise ValueError("Invalid value for `positions`, must not be `None`")  # noqa: E501

        self._positions = positions
