# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server import util


class Q24Invoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, case_no: str=None):  # noqa: E501
        """Q24Invoice - a model defined in Swagger

        :param case_no: The case_no of this Q24Invoice.  # noqa: E501
        :type case_no: str
        """
        self.swagger_types = {
            'case_no': str
        }

        self.attribute_map = {
            'case_no': 'CaseNo'
        }
        self._case_no = case_no

    @classmethod
    def from_dict(cls, dikt) -> 'Q24Invoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q24_Invoice of this Q24Invoice.  # noqa: E501
        :rtype: Q24Invoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def case_no(self) -> str:
        """Gets the case_no of this Q24Invoice.


        :return: The case_no of this Q24Invoice.
        :rtype: str
        """
        return self._case_no

    @case_no.setter
    def case_no(self, case_no: str):
        """Sets the case_no of this Q24Invoice.


        :param case_no: The case_no of this Q24Invoice.
        :type case_no: str
        """
        if case_no is None:
            raise ValueError("Invalid value for `case_no`, must not be `None`")  # noqa: E501

        self._case_no = case_no
