# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server import util


class Q2Invoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_no: str=None, name: str=None, name2: str=None, address: str=None, address2: str=None, city: str=None, post_code: str=None):  # noqa: E501
        """Q2Invoice - a model defined in Swagger

        :param invoice_no: The invoice_no of this Q2Invoice.  # noqa: E501
        :type invoice_no: str
        :param name: The name of this Q2Invoice.  # noqa: E501
        :type name: str
        :param name2: The name2 of this Q2Invoice.  # noqa: E501
        :type name2: str
        :param address: The address of this Q2Invoice.  # noqa: E501
        :type address: str
        :param address2: The address2 of this Q2Invoice.  # noqa: E501
        :type address2: str
        :param city: The city of this Q2Invoice.  # noqa: E501
        :type city: str
        :param post_code: The post_code of this Q2Invoice.  # noqa: E501
        :type post_code: str
        """
        self.swagger_types = {
            'invoice_no': str,
            'name': str,
            'name2': str,
            'address': str,
            'address2': str,
            'city': str,
            'post_code': str
        }

        self.attribute_map = {
            'invoice_no': 'InvoiceNo',
            'name': 'Name',
            'name2': 'Name2',
            'address': 'Address',
            'address2': 'Address2',
            'city': 'City',
            'post_code': 'PostCode'
        }
        self._invoice_no = invoice_no
        self._name = name
        self._name2 = name2
        self._address = address
        self._address2 = address2
        self._city = city
        self._post_code = post_code

    @classmethod
    def from_dict(cls, dikt) -> 'Q2Invoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q2_Invoice of this Q2Invoice.  # noqa: E501
        :rtype: Q2Invoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_no(self) -> str:
        """Gets the invoice_no of this Q2Invoice.


        :return: The invoice_no of this Q2Invoice.
        :rtype: str
        """
        return self._invoice_no

    @invoice_no.setter
    def invoice_no(self, invoice_no: str):
        """Sets the invoice_no of this Q2Invoice.


        :param invoice_no: The invoice_no of this Q2Invoice.
        :type invoice_no: str
        """
        if invoice_no is None:
            raise ValueError("Invalid value for `invoice_no`, must not be `None`")  # noqa: E501

        self._invoice_no = invoice_no

    @property
    def name(self) -> str:
        """Gets the name of this Q2Invoice.


        :return: The name of this Q2Invoice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Q2Invoice.


        :param name: The name of this Q2Invoice.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def name2(self) -> str:
        """Gets the name2 of this Q2Invoice.


        :return: The name2 of this Q2Invoice.
        :rtype: str
        """
        return self._name2

    @name2.setter
    def name2(self, name2: str):
        """Sets the name2 of this Q2Invoice.


        :param name2: The name2 of this Q2Invoice.
        :type name2: str
        """
        if name2 is None:
            raise ValueError("Invalid value for `name2`, must not be `None`")  # noqa: E501

        self._name2 = name2

    @property
    def address(self) -> str:
        """Gets the address of this Q2Invoice.


        :return: The address of this Q2Invoice.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Q2Invoice.


        :param address: The address of this Q2Invoice.
        :type address: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def address2(self) -> str:
        """Gets the address2 of this Q2Invoice.


        :return: The address2 of this Q2Invoice.
        :rtype: str
        """
        return self._address2

    @address2.setter
    def address2(self, address2: str):
        """Sets the address2 of this Q2Invoice.


        :param address2: The address2 of this Q2Invoice.
        :type address2: str
        """
        if address2 is None:
            raise ValueError("Invalid value for `address2`, must not be `None`")  # noqa: E501

        self._address2 = address2

    @property
    def city(self) -> str:
        """Gets the city of this Q2Invoice.


        :return: The city of this Q2Invoice.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this Q2Invoice.


        :param city: The city of this Q2Invoice.
        :type city: str
        """
        if city is None:
            raise ValueError("Invalid value for `city`, must not be `None`")  # noqa: E501

        self._city = city

    @property
    def post_code(self) -> str:
        """Gets the post_code of this Q2Invoice.


        :return: The post_code of this Q2Invoice.
        :rtype: str
        """
        return self._post_code

    @post_code.setter
    def post_code(self, post_code: str):
        """Sets the post_code of this Q2Invoice.


        :param post_code: The post_code of this Q2Invoice.
        :type post_code: str
        """
        if post_code is None:
            raise ValueError("Invalid value for `post_code`, must not be `None`")  # noqa: E501

        self._post_code = post_code
