# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q30_document import Q30Document  # noqa: F401,E501
from ods_api_server import util


class Q30Reservation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reservation: List[Q30Document]=None):  # noqa: E501
        """Q30Reservation - a model defined in Swagger

        :param reservation: The reservation of this Q30Reservation.  # noqa: E501
        :type reservation: List[Q30Document]
        """
        self.swagger_types = {
            'reservation': List[Q30Document]
        }

        self.attribute_map = {
            'reservation': 'Reservation'
        }
        self._reservation = reservation

    @classmethod
    def from_dict(cls, dikt) -> 'Q30Reservation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q30_Reservation of this Q30Reservation.  # noqa: E501
        :rtype: Q30Reservation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reservation(self) -> List[Q30Document]:
        """Gets the reservation of this Q30Reservation.


        :return: The reservation of this Q30Reservation.
        :rtype: List[Q30Document]
        """
        return self._reservation

    @reservation.setter
    def reservation(self, reservation: List[Q30Document]):
        """Sets the reservation of this Q30Reservation.


        :param reservation: The reservation of this Q30Reservation.
        :type reservation: List[Q30Document]
        """
        if reservation is None:
            raise ValueError("Invalid value for `reservation`, must not be `None`")  # noqa: E501

        self._reservation = reservation
