# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.q6_contact import Q6Contact  # noqa: F401,E501
from ods_api_server import util


class Q6ContactList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contact: List[Q6Contact]=None):  # noqa: E501
        """Q6ContactList - a model defined in Swagger

        :param contact: The contact of this Q6ContactList.  # noqa: E501
        :type contact: List[Q6Contact]
        """
        self.swagger_types = {
            'contact': List[Q6Contact]
        }

        self.attribute_map = {
            'contact': 'Contact'
        }
        self._contact = contact

    @classmethod
    def from_dict(cls, dikt) -> 'Q6ContactList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The q6_ContactList of this Q6ContactList.  # noqa: E501
        :rtype: Q6ContactList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact(self) -> List[Q6Contact]:
        """Gets the contact of this Q6ContactList.


        :return: The contact of this Q6ContactList.
        :rtype: List[Q6Contact]
        """
        return self._contact

    @contact.setter
    def contact(self, contact: List[Q6Contact]):
        """Sets the contact of this Q6ContactList.


        :param contact: The contact of this Q6ContactList.
        :type contact: List[Q6Contact]
        """
        if contact is None:
            raise ValueError("Invalid value for `contact`, must not be `None`")  # noqa: E501

        self._contact = contact
