# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_modify_hotel_bank_account_info_modify_bank_acc_info import AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo  # noqa: F401,E501
from ods_api_server import util


class TnsModifyHotelBankAccountInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_bank_acc_info: AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo=None):  # noqa: E501
        """TnsModifyHotelBankAccountInfo - a model defined in Swagger

        :param modify_bank_acc_info: The modify_bank_acc_info of this TnsModifyHotelBankAccountInfo.  # noqa: E501
        :type modify_bank_acc_info: AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo
        """
        self.swagger_types = {
            'modify_bank_acc_info': AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo
        }

        self.attribute_map = {
            'modify_bank_acc_info': 'modifyBankAccInfo'
        }
        self._modify_bank_acc_info = modify_bank_acc_info

    @classmethod
    def from_dict(cls, dikt) -> 'TnsModifyHotelBankAccountInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ModifyHotelBankAccountInfo of this TnsModifyHotelBankAccountInfo.  # noqa: E501
        :rtype: TnsModifyHotelBankAccountInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_bank_acc_info(self) -> AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo:
        """Gets the modify_bank_acc_info of this TnsModifyHotelBankAccountInfo.


        :return: The modify_bank_acc_info of this TnsModifyHotelBankAccountInfo.
        :rtype: AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo
        """
        return self._modify_bank_acc_info

    @modify_bank_acc_info.setter
    def modify_bank_acc_info(self, modify_bank_acc_info: AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo):
        """Sets the modify_bank_acc_info of this TnsModifyHotelBankAccountInfo.


        :param modify_bank_acc_info: The modify_bank_acc_info of this TnsModifyHotelBankAccountInfo.
        :type modify_bank_acc_info: AllOftnsModifyHotelBankAccountInfoModifyBankAccInfo
        """
        if modify_bank_acc_info is None:
            raise ValueError("Invalid value for `modify_bank_acc_info`, must not be `None`")  # noqa: E501

        self._modify_bank_acc_info = modify_bank_acc_info
