# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_insert_payment_v2_insert_payment import AllOftnsInsertPaymentV2InsertPayment  # noqa: F401,E501
from ods_api_server import util


class TnsInsertPaymentV2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment: AllOftnsInsertPaymentV2InsertPayment=None):  # noqa: E501
        """TnsInsertPaymentV2 - a model defined in Swagger

        :param insert_payment: The insert_payment of this TnsInsertPaymentV2.  # noqa: E501
        :type insert_payment: AllOftnsInsertPaymentV2InsertPayment
        """
        self.swagger_types = {
            'insert_payment': AllOftnsInsertPaymentV2InsertPayment
        }

        self.attribute_map = {
            'insert_payment': 'insertPayment'
        }
        self._insert_payment = insert_payment

    @classmethod
    def from_dict(cls, dikt) -> 'TnsInsertPaymentV2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_InsertPaymentV2 of this TnsInsertPaymentV2.  # noqa: E501
        :rtype: TnsInsertPaymentV2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment(self) -> AllOftnsInsertPaymentV2InsertPayment:
        """Gets the insert_payment of this TnsInsertPaymentV2.


        :return: The insert_payment of this TnsInsertPaymentV2.
        :rtype: AllOftnsInsertPaymentV2InsertPayment
        """
        return self._insert_payment

    @insert_payment.setter
    def insert_payment(self, insert_payment: AllOftnsInsertPaymentV2InsertPayment):
        """Sets the insert_payment of this TnsInsertPaymentV2.


        :param insert_payment: The insert_payment of this TnsInsertPaymentV2.
        :type insert_payment: AllOftnsInsertPaymentV2InsertPayment
        """
        if insert_payment is None:
            raise ValueError("Invalid value for `insert_payment`, must not be `None`")  # noqa: E501

        self._insert_payment = insert_payment
