# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_change_customer_address_v2_customer_address import AllOftnsChangeCustomerAddressV2CustomerAddress  # noqa: F401,E501
from ods_api_server import util


class TnsChangeCustomerAddressV2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_address: AllOftnsChangeCustomerAddressV2CustomerAddress=None):  # noqa: E501
        """TnsChangeCustomerAddressV2 - a model defined in Swagger

        :param customer_address: The customer_address of this TnsChangeCustomerAddressV2.  # noqa: E501
        :type customer_address: AllOftnsChangeCustomerAddressV2CustomerAddress
        """
        self.swagger_types = {
            'customer_address': AllOftnsChangeCustomerAddressV2CustomerAddress
        }

        self.attribute_map = {
            'customer_address': 'customerAddress'
        }
        self._customer_address = customer_address

    @classmethod
    def from_dict(cls, dikt) -> 'TnsChangeCustomerAddressV2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ChangeCustomerAddressV2 of this TnsChangeCustomerAddressV2.  # noqa: E501
        :rtype: TnsChangeCustomerAddressV2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_address(self) -> AllOftnsChangeCustomerAddressV2CustomerAddress:
        """Gets the customer_address of this TnsChangeCustomerAddressV2.


        :return: The customer_address of this TnsChangeCustomerAddressV2.
        :rtype: AllOftnsChangeCustomerAddressV2CustomerAddress
        """
        return self._customer_address

    @customer_address.setter
    def customer_address(self, customer_address: AllOftnsChangeCustomerAddressV2CustomerAddress):
        """Sets the customer_address of this TnsChangeCustomerAddressV2.


        :param customer_address: The customer_address of this TnsChangeCustomerAddressV2.
        :type customer_address: AllOftnsChangeCustomerAddressV2CustomerAddress
        """
        if customer_address is None:
            raise ValueError("Invalid value for `customer_address`, must not be `None`")  # noqa: E501

        self._customer_address = customer_address
