# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_confirm_invoice_confirm_invoice import AllOftnsConfirmInvoiceConfirmInvoice  # noqa: F401,E501
from ods_api_server import util


class TnsConfirmInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, confirm_invoice: AllOftnsConfirmInvoiceConfirmInvoice=None):  # noqa: E501
        """TnsConfirmInvoice - a model defined in Swagger

        :param confirm_invoice: The confirm_invoice of this TnsConfirmInvoice.  # noqa: E501
        :type confirm_invoice: AllOftnsConfirmInvoiceConfirmInvoice
        """
        self.swagger_types = {
            'confirm_invoice': AllOftnsConfirmInvoiceConfirmInvoice
        }

        self.attribute_map = {
            'confirm_invoice': 'confirmInvoice'
        }
        self._confirm_invoice = confirm_invoice

    @classmethod
    def from_dict(cls, dikt) -> 'TnsConfirmInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ConfirmInvoice of this TnsConfirmInvoice.  # noqa: E501
        :rtype: TnsConfirmInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def confirm_invoice(self) -> AllOftnsConfirmInvoiceConfirmInvoice:
        """Gets the confirm_invoice of this TnsConfirmInvoice.


        :return: The confirm_invoice of this TnsConfirmInvoice.
        :rtype: AllOftnsConfirmInvoiceConfirmInvoice
        """
        return self._confirm_invoice

    @confirm_invoice.setter
    def confirm_invoice(self, confirm_invoice: AllOftnsConfirmInvoiceConfirmInvoice):
        """Sets the confirm_invoice of this TnsConfirmInvoice.


        :param confirm_invoice: The confirm_invoice of this TnsConfirmInvoice.
        :type confirm_invoice: AllOftnsConfirmInvoiceConfirmInvoice
        """
        if confirm_invoice is None:
            raise ValueError("Invalid value for `confirm_invoice`, must not be `None`")  # noqa: E501

        self._confirm_invoice = confirm_invoice
