# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_modify_invoice_modify_invoice import AllOftnsModifyInvoiceModifyInvoice  # noqa: F401,E501
from ods_api_server import util


class TnsModifyInvoice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_invoice: AllOftnsModifyInvoiceModifyInvoice=None):  # noqa: E501
        """TnsModifyInvoice - a model defined in Swagger

        :param modify_invoice: The modify_invoice of this TnsModifyInvoice.  # noqa: E501
        :type modify_invoice: AllOftnsModifyInvoiceModifyInvoice
        """
        self.swagger_types = {
            'modify_invoice': AllOftnsModifyInvoiceModifyInvoice
        }

        self.attribute_map = {
            'modify_invoice': 'modifyInvoice'
        }
        self._modify_invoice = modify_invoice

    @classmethod
    def from_dict(cls, dikt) -> 'TnsModifyInvoice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ModifyInvoice of this TnsModifyInvoice.  # noqa: E501
        :rtype: TnsModifyInvoice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_invoice(self) -> AllOftnsModifyInvoiceModifyInvoice:
        """Gets the modify_invoice of this TnsModifyInvoice.


        :return: The modify_invoice of this TnsModifyInvoice.
        :rtype: AllOftnsModifyInvoiceModifyInvoice
        """
        return self._modify_invoice

    @modify_invoice.setter
    def modify_invoice(self, modify_invoice: AllOftnsModifyInvoiceModifyInvoice):
        """Sets the modify_invoice of this TnsModifyInvoice.


        :param modify_invoice: The modify_invoice of this TnsModifyInvoice.
        :type modify_invoice: AllOftnsModifyInvoiceModifyInvoice
        """
        if modify_invoice is None:
            raise ValueError("Invalid value for `modify_invoice`, must not be `None`")  # noqa: E501

        self._modify_invoice = modify_invoice
