# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_change_contact_information_contact_information import AllOftnsChangeContactInformationContactInformation  # noqa: F401,E501
from ods_api_server import util


class TnsChangeContactInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contact_information: AllOftnsChangeContactInformationContactInformation=None):  # noqa: E501
        """TnsChangeContactInformation - a model defined in Swagger

        :param contact_information: The contact_information of this TnsChangeContactInformation.  # noqa: E501
        :type contact_information: AllOftnsChangeContactInformationContactInformation
        """
        self.swagger_types = {
            'contact_information': AllOftnsChangeContactInformationContactInformation
        }

        self.attribute_map = {
            'contact_information': 'contactInformation'
        }
        self._contact_information = contact_information

    @classmethod
    def from_dict(cls, dikt) -> 'TnsChangeContactInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ChangeContactInformation of this TnsChangeContactInformation.  # noqa: E501
        :rtype: TnsChangeContactInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contact_information(self) -> AllOftnsChangeContactInformationContactInformation:
        """Gets the contact_information of this TnsChangeContactInformation.


        :return: The contact_information of this TnsChangeContactInformation.
        :rtype: AllOftnsChangeContactInformationContactInformation
        """
        return self._contact_information

    @contact_information.setter
    def contact_information(self, contact_information: AllOftnsChangeContactInformationContactInformation):
        """Sets the contact_information of this TnsChangeContactInformation.


        :param contact_information: The contact_information of this TnsChangeContactInformation.
        :type contact_information: AllOftnsChangeContactInformationContactInformation
        """
        if contact_information is None:
            raise ValueError("Invalid value for `contact_information`, must not be `None`")  # noqa: E501

        self._contact_information = contact_information
