# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_change_customer_address_customer_address import AllOftnsChangeCustomerAddressCustomerAddress  # noqa: F401,E501
from ods_api_server import util


class TnsChangeCustomerAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, customer_address: AllOftnsChangeCustomerAddressCustomerAddress=None):  # noqa: E501
        """TnsChangeCustomerAddress - a model defined in Swagger

        :param customer_address: The customer_address of this TnsChangeCustomerAddress.  # noqa: E501
        :type customer_address: AllOftnsChangeCustomerAddressCustomerAddress
        """
        self.swagger_types = {
            'customer_address': AllOftnsChangeCustomerAddressCustomerAddress
        }

        self.attribute_map = {
            'customer_address': 'customerAddress'
        }
        self._customer_address = customer_address

    @classmethod
    def from_dict(cls, dikt) -> 'TnsChangeCustomerAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ChangeCustomerAddress of this TnsChangeCustomerAddress.  # noqa: E501
        :rtype: TnsChangeCustomerAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def customer_address(self) -> AllOftnsChangeCustomerAddressCustomerAddress:
        """Gets the customer_address of this TnsChangeCustomerAddress.


        :return: The customer_address of this TnsChangeCustomerAddress.
        :rtype: AllOftnsChangeCustomerAddressCustomerAddress
        """
        return self._customer_address

    @customer_address.setter
    def customer_address(self, customer_address: AllOftnsChangeCustomerAddressCustomerAddress):
        """Sets the customer_address of this TnsChangeCustomerAddress.


        :param customer_address: The customer_address of this TnsChangeCustomerAddress.
        :type customer_address: AllOftnsChangeCustomerAddressCustomerAddress
        """
        if customer_address is None:
            raise ValueError("Invalid value for `customer_address`, must not be `None`")  # noqa: E501

        self._customer_address = customer_address
