# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_change_invoice_address_invoice_address import AllOftnsChangeInvoiceAddressInvoiceAddress  # noqa: F401,E501
from ods_api_server import util


class TnsChangeInvoiceAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, invoice_address: AllOftnsChangeInvoiceAddressInvoiceAddress=None):  # noqa: E501
        """TnsChangeInvoiceAddress - a model defined in Swagger

        :param invoice_address: The invoice_address of this TnsChangeInvoiceAddress.  # noqa: E501
        :type invoice_address: AllOftnsChangeInvoiceAddressInvoiceAddress
        """
        self.swagger_types = {
            'invoice_address': AllOftnsChangeInvoiceAddressInvoiceAddress
        }

        self.attribute_map = {
            'invoice_address': 'invoiceAddress'
        }
        self._invoice_address = invoice_address

    @classmethod
    def from_dict(cls, dikt) -> 'TnsChangeInvoiceAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ChangeInvoiceAddress of this TnsChangeInvoiceAddress.  # noqa: E501
        :rtype: TnsChangeInvoiceAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def invoice_address(self) -> AllOftnsChangeInvoiceAddressInvoiceAddress:
        """Gets the invoice_address of this TnsChangeInvoiceAddress.


        :return: The invoice_address of this TnsChangeInvoiceAddress.
        :rtype: AllOftnsChangeInvoiceAddressInvoiceAddress
        """
        return self._invoice_address

    @invoice_address.setter
    def invoice_address(self, invoice_address: AllOftnsChangeInvoiceAddressInvoiceAddress):
        """Sets the invoice_address of this TnsChangeInvoiceAddress.


        :param invoice_address: The invoice_address of this TnsChangeInvoiceAddress.
        :type invoice_address: AllOftnsChangeInvoiceAddressInvoiceAddress
        """
        if invoice_address is None:
            raise ValueError("Invalid value for `invoice_address`, must not be `None`")  # noqa: E501

        self._invoice_address = invoice_address
