# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_insert_payment_insert_payment import AllOftnsInsertPaymentInsertPayment  # noqa: F401,E501
from ods_api_server import util


class TnsInsertPayment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, insert_payment: AllOftnsInsertPaymentInsertPayment=None):  # noqa: E501
        """TnsInsertPayment - a model defined in Swagger

        :param insert_payment: The insert_payment of this TnsInsertPayment.  # noqa: E501
        :type insert_payment: AllOftnsInsertPaymentInsertPayment
        """
        self.swagger_types = {
            'insert_payment': AllOftnsInsertPaymentInsertPayment
        }

        self.attribute_map = {
            'insert_payment': 'insertPayment'
        }
        self._insert_payment = insert_payment

    @classmethod
    def from_dict(cls, dikt) -> 'TnsInsertPayment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_InsertPayment of this TnsInsertPayment.  # noqa: E501
        :rtype: TnsInsertPayment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def insert_payment(self) -> AllOftnsInsertPaymentInsertPayment:
        """Gets the insert_payment of this TnsInsertPayment.


        :return: The insert_payment of this TnsInsertPayment.
        :rtype: AllOftnsInsertPaymentInsertPayment
        """
        return self._insert_payment

    @insert_payment.setter
    def insert_payment(self, insert_payment: AllOftnsInsertPaymentInsertPayment):
        """Sets the insert_payment of this TnsInsertPayment.


        :param insert_payment: The insert_payment of this TnsInsertPayment.
        :type insert_payment: AllOftnsInsertPaymentInsertPayment
        """
        if insert_payment is None:
            raise ValueError("Invalid value for `insert_payment`, must not be `None`")  # noqa: E501

        self._insert_payment = insert_payment
