# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ods_api_server.models.base_model_ import Model
from ods_api_server.models.all_oftns_modify_hotel_credit_card_info_modify_credit_card_info import AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo  # noqa: F401,E501
from ods_api_server import util


class TnsModifyHotelCreditCardInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, modify_credit_card_info: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo=None):  # noqa: E501
        """TnsModifyHotelCreditCardInfo - a model defined in Swagger

        :param modify_credit_card_info: The modify_credit_card_info of this TnsModifyHotelCreditCardInfo.  # noqa: E501
        :type modify_credit_card_info: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo
        """
        self.swagger_types = {
            'modify_credit_card_info': AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo
        }

        self.attribute_map = {
            'modify_credit_card_info': 'modifyCreditCardInfo'
        }
        self._modify_credit_card_info = modify_credit_card_info

    @classmethod
    def from_dict(cls, dikt) -> 'TnsModifyHotelCreditCardInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tns_ModifyHotelCreditCardInfo of this TnsModifyHotelCreditCardInfo.  # noqa: E501
        :rtype: TnsModifyHotelCreditCardInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def modify_credit_card_info(self) -> AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo:
        """Gets the modify_credit_card_info of this TnsModifyHotelCreditCardInfo.


        :return: The modify_credit_card_info of this TnsModifyHotelCreditCardInfo.
        :rtype: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo
        """
        return self._modify_credit_card_info

    @modify_credit_card_info.setter
    def modify_credit_card_info(self, modify_credit_card_info: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo):
        """Sets the modify_credit_card_info of this TnsModifyHotelCreditCardInfo.


        :param modify_credit_card_info: The modify_credit_card_info of this TnsModifyHotelCreditCardInfo.
        :type modify_credit_card_info: AllOftnsModifyHotelCreditCardInfoModifyCreditCardInfo
        """
        if modify_credit_card_info is None:
            raise ValueError("Invalid value for `modify_credit_card_info`, must not be `None`")  # noqa: E501

        self._modify_credit_card_info = modify_credit_card_info
